### ISSUE TITLE
Integration in R^d

### ISSUE THREAD

**Issue by YazidJanati** [ndeutschmann/zunis#12]
Hi! 

How can this be used for general integration problems? It seems that this is limited to integration over the hypercube. 

What if i want to estimate normalizing constants of densities supported in R^d? 

Thank you in advance.

**Comment by ndeutschmann** [comment]
Hi Yazid,

If you are integrating over R^d, you can always map back to the unit hypercube by a change of variables that maps [0,1] to R. For example, you could use 

<img width="928" alt="image" src="https://user-images.githubusercontent.com/12328649/112145349-8676dc00-8bda-11eb-98ba-cd92f9106d88.png">

But any bijective function that has two divergences is suitable (arctanh would work too for example)

Note BTW that in practice this is how you would define sampling over all of R. The "naive" method of sampling uniformly over a large enough interval yields an estimator with infinite variance.

**Comment by ndeutschmann** [comment]
NB: I think it would be a good idea to include a function wrapper to do this automatically in zunis.utils.function_wrapper, which already has tools to remap arbitrary intervals to the unit hypercube. In the meantime I would advise you to just implement a change of variable like the one above by hand.

**Comment by YazidJanati** [comment]
Thank you for your quick and useful answer.
