### ISSUE TITLE
the code of ‘One-blob encoding’

### ISSUE THREAD

**Issue by Haotian-CS** [ndeutschmann/zunis#16]
I can' not find the code of 'One-Blob encoding'.

I don't know how to deal the input.

Thanks!

**Comment by ndeutschmann** [comment]
Hi, ZuNIS does not implement one blob encoding, which is why you did not find anything about it here ;)

**Comment by Haotian-CS** [comment]
Thanks! 

How to use the Gaussian kernel？I don't quite understand here. Looking forward to your reply.
![image](https://user-images.githubusercontent.com/37902118/117423214-0f5f9200-af53-11eb-80e5-1ab20bab2e25.png)


Could you please share the relevant code if possible?

**Comment by ndeutschmann** [comment]
I don't believe this question has anything to do with ZüNIS. This board is specifically to raise issues or ask questions about the library.
