### ISSUE TITLE
log determinant calculation numerically unstable

### ISSUE THREAD

**Issue by kevjshih** [ndeutschmann/zunis#28]
This is a fantastic library with great documentation! I just wanted to throw in a suggestion that the log determinant calculations be fixed to use the sum of logs instead of the log of products. The current implementation does tend to result in infs when dealing with higher dimensional data.

https://github.com/ndeutschmann/zunis/blob/1a75e005c6ee4652f9f3abf64ce9d14d32e5b2c1/zunis_lib/zunis/models/flows/coupling_cells/piecewise_coupling/piecewise_linear.py#L75

**Comment by ndeutschmann** [comment]
That’s a good point, I’ll fix this in the coming days. Many thanks!

**Comment by ndeutschmann** [comment]
Fixed with #37. Thanks again for pointing it out!
